### ISSUE TITLE
Install didn't work

### ISSUE THREAD

**Issue by wqhf** [wwcrc/cnv_facets#1]
Hello dariober,
I try to install cnv_facets on centos7.2 but it doesn't work.
I just followed your readme file.
the error message like:
```
Error: bin directory requested by -b/--bin_dir '/root/bin' is not on PATH
```
I also try several ways but it failed too
```
[root@wulab cnv_facets-src]# bash setup.sh -b ../
Error: bin directory requested by -b/--bin_dir '../' is not on PATH
[root@wulab cnv_facets-src]# bash setup.sh -b ../cnv_facets
Error: bin directory requested by -b/--bin_dir '../cnv_facets' is not on PATH
[root@wulab cnv_facets-src]# bash setup.sh -b /data2/database/opt/common/cnv_facets/cnv_facets
Error: bin directory requested by -b/--bin_dir '/data2/database/opt/common/cnv_facets/cnv_facets' is not on PATH
```

**Comment by dariober** [comment]
Hi- As the error message says, it appears the directory you chose to install to via the `-b` option is not on your PATH. 

To see what directories are on your PATH execute `echo $PATH` and either choose a directory where you can write or create a new directory and add it to your PATH. 

A common directory for installing custom programs like `cnv_facets.R` is `$HOME/bin` or `/usr/local/bin` (but this latter requires admin rights to write to). 

I would suggest working as regular user not as **root**, as it seems from your code blocks.

Putting it all together, what you can do as **regular** user (not root): 

* Create a personal bin directory

```
mkdir -p $HOME/bin  
```

* Add this directory to your PATH (it may be already on your PATH, check the output of `echo $PATH`, maybe post the output of `echo $PATH` here)

```
echo 'export PATH=$HOME/bin:$PATH' >> ~/.bash_profile
source ~/.bash_profile
``` 

* Install cnv_facets:

```
bash setup.sh -b $HOME/bin
```

Let me know how you get on and feel free to report back any further issues you may have...

**Comment by dariober** [comment]
Hi- If still interested, *cnv_facets* can be installed now with [bioconda](https://bioconda.github.io/recipes/cnv_facets/README.html). I recommend this route rather the `setup.sh` script.
